export const PINNED_APPS_KEY = 'pinnedApps';
export const PINNED_DOCK_APPS_KEY = 'pinnedDockApps';
export const ICON_OVERRIDES: Record<string, string> = {
	youtube: 'google_youtube.png',
	yt_music: 'google_youtube_music.png',
	ajustes: 'settings.png',
	'1.1.1.1': '_1111.png',
	aeat: 'agencia_tributaria_aeat.png',
	amazon_compras: 'amazon.png',
	asistente: 'google_assistant.png',
	calendario: 'google_calendar.png',
	calculadora: 'google_calculator',
	camara: 'camera.png',
	chatgpt: 'chat___gpt.png',
	'cl@ve': 'clave_pin.png',
	contactos: 'contacts.png',
	documentos: 'google_documents.png',
	chrome: 'chrome.png',
	drive: 'google_drive.png',
	el_tiempo_de_pixel: 'weather.png',
	encontrar_mi_dispositivo: 'google_find_device.png',
	files_by_google: 'google_files.png',
	fotos: 'google_photos.png',
	gemini: 'google_gemini.png',
	gmail: 'google_mail.png',
	google: 'google_search.png',
	google_play_store: 'google_playstore.png',
	google_tv: 'google_tv_12.png',
	google_wallet: 'google_wallet_22.png',
	grabadora: 'google_recorder.png',
	home: 'google_home_12.png',
	jira: 'jira_cloud_atlassian.png',
	keepassdx: 'keepass.png',
	kfc_españa: 'kfc.png',
	maps: 'google_maps.png',
	material_files: 'google_files.png',
	meet: 'google_meet.png',
	mensajes: 'google_messages.png',
	mi_movistar: 'movistar.png',
	mi_orange: 'orange.png',
	mi_vodafone: 'vodafone.png',
	notas_de_keep: 'google_keep.png',
	pixel_buds: 'google_pixel_buds.png',
	play_console: 'google_playconsole.png',
	prime_video: 'amazon_prime_video.png',
	reddit: 'reddit1.png',
	reloj: 'clock.png',
	revanced_manager: 're__vanced.png',
	square_home: 'square__home_2.png',
	teléfono: 'google_phone_12.png',
	termómetro: 'google_pixel_thermometer.png',
	threads: 'threads_instagram.png',
	traductor: 'google_translate.png',
	whatsapp: 'whatsapp.png',
};
export const PACKAGE_NAME_ALIASES: Record<string, string[]> = {
	'app.revanced.manager.flutter': ['manager', 'revanced'],
	'com.google.android.accessibility.switchaccess': ['accessibility', 'accesibilidad', 'interruptores', 'con'],
	'com.google.android.dialer': ['phone', 'dialer', 'call', 'teléfono', 'llamar'],
	'com.google.android.apps.messaging': ['messages', 'sms', 'text', 'mensajes'],
	'com.android.settings': ['settings', 'ajustes', 'configuración'],
	'com.amazon.mShop.android.shopping': ['amazon', 'shopping', 'compras'],
	'com.cirici.casaametller': ['casa ametller', 'casa', 'ametller', 'origen'],
	'com.dylan.win11.app.extractor': ['apk', 'extractor', 'pro'],
	'com.google.android.apps.authenticator2': ['authenticator', 'autenticador', '2fa', 'two factor', 'google authenticator'],
	'com.azure.authenticator': ['authenticator', 'autenticador', '2fa', 'two factor', 'microsoft authenticator'],
	'com.backmarket': ['backmarket', 'back market', 'backmarket.es', 'backmarket france', 'backmarket fr', 'second hand', 'segunda mano', 'reacondicionado', 'refurbished'],
	'consumerapp.bsmart.bcits.JVVNLcis': ['jvvnl', 'jvvnl cis', 'jvvnl consumer app', 'jvvnl app', 'jvvnl rajasthan', 'electricity', 'electricidad', 'electricity bill', 'factura de electricidad'],
	'xyz.blueskyweb.app': ['bluesky', 'bluesky web', 'bluesky social', 'social media', 'social', 'redes sociales'],
	'com.bunq.android': ['bunq', 'banking', 'banco', 'banca', 'finanzas'],
	'com.google.android.calculator': ['calculator', 'calculadora'],
	'com.canva.editor': ['canva', 'editor', 'diseño', 'design'],
	'com.caprabo.app': ['caprabo', 'supermercado', 'supermarket', 'compras', 'groceries'],
	'cat.atm.cartera': ['carta', 'cartera', 'atm', 'atmcarta', 'atmcarta.cat', 'atmcarta app', 'atm app', 'wallet', 'billete', 'ticket'],
	'cat.atm.tmobilitat': ['t-mobilitat'],
	'cat.gencat.mobi.rodalies': ['rodalies'],
	'club.incendiarypigs.mur': ['mur'],
	'cn.gavinliu.snapmod': ['snapmod'],
	'com.Oney.OneyApp': ['españa', 'oney'],
	'com.Slack': ['slack'],
	'com.automattic.simplenote': ['simplenote'],
	'com.b_lam.resplash': ['resplash'],
	'com.einnovation.temu': ['temu'],
	'com.geomobile.tmbmobile': ['tmbapp'],
	'com.google.android.apps.pixel.health': ['termómetro'],
	'com.google.android.apps.playconsole': ['play', 'console'],
	'com.google.android.apps.wearables.maestro.companion': ['pixel', 'buds'],
	'com.google.audio.hearing.visualization.accessibility.scribe': ['sonidos', 'notificaciones', 'instantánea', 'de', 'transcripción', 'y'],
	'com.instagram.barcelona': ['threads'],
	'com.paraskcd.unitedwalls': ['walls', 'united'],
	'com.paypal.android.p2pmobile': ['paypal'],
	'com.picsart.studio': ['picsart'],
	'com.rebtel.android': ['rebtel'],
	'com.reddit.frontpage': ['reddit'],
	'com.remitly.androidapp': ['remitly'],
	'com.sequra.app': ['sequra'],
	'com.shazam.android': ['shazam'],
	'com.ss.squarehome2': ['home', 'square'],
	'com.squarespace.android.squarespaceapp': ['squarespace'],
	'com.suno.android': ['suno'],
	'com.tailscale.ipn': ['tailscale'],
	'com.termux': ['termux'],
	'com.tinder': ['tinder'],
	'com.tozelabs.tvshowtime': ['time', 'tv'],
	'com.toggl.giskard': ['toggltrack'],
	'com.westernunion.moneytransferr3app.es': ['westernunion'],
	'com.whicons.iconpack': ['whicons'],
	'com.wireguard.android': ['wireguard'],
	'de.number26.android': ['n26'],
	'it.very.mobile': ['very'],
	'net.openvpn.openvpn': ['security', 'openvpn', 'seguridad', 'vpn', 'connect'],
	'com.cetelem.HomeBanking': ['cetelem', 'home banking', 'banco', 'finanzas', 'banking'],
	'com.android.chrome': ['chrome', 'browser', 'navegador', 'web'],
	'es.cineyelmo': ['cine', 'yelmocine', 'yelmocine.es', 'yelmocine app', 'yelmocine cinema', 'yelmocine movie', 'movie tickets', 'entradas de cine'],
	'es.aeat.pin24h': ['clave'],
	'es.gob.afirma': ['firma', 'firma electrónica', 'firma digital', 'afirma'],
	'com.discord': ['discord', 'chat', 'comunidad', 'server', 'servidor'],
	'com.google.android.apps.docs.editors.docs': ['docs', 'documentos', 'google docs', 'editor de documentos'],
	'com.google.android.apps.docs.editors.sheets': ['sheets', 'hojas de cálculo', 'google sheets', 'editor de hojas de cálculo'],
	'com.google.android.apps.docs.editors.slides': ['slides', 'presentaciones', 'google slides', 'editor de presentaciones'],
	'com.google.android.apps.docs': ['drive', 'google drive', 'almacenamiento', 'storage'],
	'com.google.android.apps.weather': ['weather', 'clima', 'tiempo', 'meteorología'],
	'com.google.android.apps.safetyhub': ['safety', 'seguridad', 'safety hub', 'seguridad hub', 'sos'],
	'com.mttnow.android.etihad': ['etihad', 'etihad airways', 'airlines', 'aerolínea', 'vuelo', 'flight'],
	'com.google.android.apps.nbu.files': ['files', 'archivos', 'file manager', 'gestor de archivos'],
	'org.mozilla.firefox': ['firefox', 'browser', 'navegador', 'web'],
	'com.google.android.apps.photos': ['photos', 'fotos', 'galería', 'google photos'],
	'com.google.android.apps.photosgo': ['photos', 'fotos', 'galería', 'google photos'],
	'com.google.android.apps.bard': ['bard', 'google bard', 'ai', 'inteligencia artificial'],
	'com.openai.chatgpt': ['chatgpt', 'openai', 'inteligencia artificial', 'ai'],
	'com.github.android': ['github', 'git', 'repositorio', 'repository', 'código', 'code'],
	'com.glovo': ['glovo', 'delivery', 'entrega', 'reparto', 'food delivery'],
	'com.google.android.gm': ['gmail', 'email', 'correo', 'mail'],
	'com.google.android.googlequicksearchbox': ['search', 'google search', 'búsqueda', 'google'],
	'com.google.android.apps.magazines': ['news', 'noticias', 'google news', 'revistas', 'magazines'],
	'com.android.vending': ['play store', 'google play', 'store', 'tienda', 'apps'],
	'com.google.android.videos': ['google videos', 'vídeos', 'video'],
	'com.google.android.apps.walletnfcrel': ['wallet', 'google wallet', 'pago', 'payments', 'pagos'],
	'com.google.android.apps.recorder': ['recorder', 'grabadora', 'grabación', 'audio recorder'],
	'ai.x.grok': ['grok', 'x', 'ai', 'x.com', 'inteligencia artificial'],
	'com.gumroad.app': ['gumroad', 'compras', 'shopping', 'marketplace'],
	'org.illegaller.ratabb.hishoot2i': ['hishoot2i', 'hishoot', 'ratabb', 'camera', 'fotografía', 'photo'],
	'com.holded.app': ['holded', 'finanzas', 'banco', 'banking', 'contabilidad', 'accounting', 'salary', 'nómina', 'invoices', 'facturas', 'salario'],
	'com.google.android.apps.chromecast.app': ['chromecast', 'cast', 'streaming', 'google cast', 'google home'],
	'com.idealista.android': ['idealista', 'inmobiliaria', 'real estate', 'propiedades', 'properties'],
	'com.instagram.android': ['instagram', 'ig', 'social media', 'redes sociales', 'social'],
	'com.atlassian.android.jira.core': ['jira', 'atlassian', 'project management', 'gestión de proyectos', 'task management', 'gestión de tareas', 'agile', 'scrum'],
	'com.kunzisoft.keepass.free': ['keepass', 'password manager', 'gestor de contraseñas', 'passwords'],
	'es.kfc.spain': ['kfc', 'fast food', 'comida rápida', 'pollo', 'chicken'],
	'com.myklarnamobile': ['klarna', 'finanzas', 'banco', 'banking', 'compras', 'shopping'],
	'cat.gencat.mobi.lamevasalut': ['meu salut', 'meu salut app', 'salut', 'salud', 'health', 'sanidad', 'cat salut'],
	'com.readygo.barrel.gp': ['barrel', 'barrel app', 'barrel game', 'juego', 'game'],
	'com.linkedin.android': ['linkedin', 'social media', 'redes sociales', 'networking', 'empleo', 'jobs'],
	'com.google.android.apps.adm': ['find my device', 'find my phone', 'google find my device', 'localización', 'ubicación', 'device manager'],
	'com.google.android.apps.maps': ['google maps', 'maps', 'mapas', 'navegación', 'navigation'],
	'org.joinmastodon.android': ['mastodon', 'social media', 'redes sociales', 'fediverse', 'social'],
	'me.zhanghai.android.files': ['files', 'archivos', 'file manager', 'gestor de archivos'],
	'com.google.android.apps.tachyon': ['duo', 'google duo', 'videollamadas', 'videocalls', 'video calls'],
	'es.mercadona.tienda': ['mercadona', 'supermercado', 'supermarket', 'compras', 'groceries'],
	'com.movistar.android.mimovistar.es': ['mi movistar', 'movistar', 'telecomunicaciones', 'telecom', 'telefonía', 'mobile'],
	'com.orange.miorange': ['mi orange', 'orange', 'telecomunicaciones', 'telecom', 'telefonía', 'mobile'],
	'es.vodafone.mobile.mivodafone': ['mi vodafone', 'vodafone', 'telecomunicaciones', 'telecom', 'telefonía', 'mobile'],
	'com.realtimeboard': ['miro', 'miro app', 'collaboration', 'colaboración', 'whiteboard', 'pizarra'],
	'net.mullvad.mullvadvpn': ['mullvad', 'vpn', 'virtual private network', 'red privada virtual'],
	'com.google.android.calendar': ['calendar', 'calendario', 'agenda', 'google calendar', 'eventos', 'events'],
	'com.google.android.GoogleCamera': ['camera', 'photo', 'foto', 'cámara', 'fotografía', 'google camera'],
	'com.google.android.deskclock': ['clock', 'reloj', 'alarm', 'alarma', 'timer', 'cronómetro'],
	'com.google.android.youtube': ['youtube', 'yt', 'vídeos', 'video', 'streaming', 'google youtube'],
	'com.google.android.apps.translate': ['translate', 'traductor', 'traducción', 'google translate', 'google traductor'],
	'com.google.android.contacts': ['contacts', 'contactos', 'agenda', 'teléfono', 'phone'],
	'com.google.android.keep': ['notes', 'notas', 'keep', 'google keep'],
	'com.google.android.apps.youtube.music': ['music', 'player', 'música', 'yt music', 'youtube music'],
	'com.whatsapp': ['whatsapp', 'chat', 'mensaje', 'mensajería', 'whatsapp messenger'],
	'com.twitter.android': ['twitter', 'x', 'tweets', 'red social', 'social media', 'social'],
	'com.facebook.katana': ['facebook', 'fb', 'social', 'redes sociales', 'social media'],
	'org.telegram.messenger': ['telegram', 'chat', 'mensajería', 'messaging'],
};
